services:
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chromadb
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma_data

  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_chatbot
    ports:
      - "7860:7860"  # Gradio frontend
    environment:
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
    volumes:
      - .:/app
    command: python rag_loop.py
    depends_on:
      - chromadb

volumes:
  chroma_data: {}