version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - chromadb

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma_data

  chatbot:
    build: .
    ports:
      - "7860:7860"
    environment:
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
    volumes:
      - .:/app
    command: python rag_loop.py

volumes:
  chroma_data: {}
